name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Check ${{ matrix.test }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [ 'unit-test', 'phpcs', 'psalm', 'phpstan' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer run ${{ matrix.test }}